<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (DB::table('currencies')->exists()) {
            return;
        }

        $items = [
            [
                'code' => 'AED',
                'label' => 'United Arab Emirates dirham',
                'is_active' => true,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'AFN',
                'label' => 'Afghan afghani',
                'is_active' => true,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ALL',
                'label' => 'Albanian lek',
                'is_active' => true,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'AMD',
                'label' => 'Armenian dram',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ANG',
                'label' => 'Netherlands Antillean guilder',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'AOA',
                'label' => 'Angolan kwanza',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ARS',
                'label' => 'Argentine peso',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'AUD',
                'label' => 'Australian dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'AWG',
                'label' => 'Aruban florin',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'AZN',
                'label' => 'Azerbaijani manat',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BAM',
                'label' => 'Bosnia and Herzegovina convertible mark',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BBD',
                'label' => 'Barbadian dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BDT',
                'label' => 'Bangladeshi taka',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BGN',
                'label' => 'Bulgarian lev',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BHD',
                'label' => 'Bahraini dinar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BIF',
                'label' => 'Burundian franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BMD',
                'label' => 'Bermudian dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BND',
                'label' => 'Brunei dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BOB',
                'label' => 'Bolivian boliviano',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BRL',
                'label' => 'Brazilian real',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BSD',
                'label' => 'Bahamian dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BTN',
                'label' => 'Bhutanese ngultrum',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BWP',
                'label' => 'Botswana pula',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BYN',
                'label' => 'Belarusian ruble',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'BZD',
                'label' => 'Belize dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CAD',
                'label' => 'Canadian dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CDF',
                'label' => 'Congolese franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CHE',
                'label' => 'WIR Euro',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CHF',
                'label' => 'Swiss franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CHW',
                'label' => 'WIR Franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CLP',
                'label' => 'Chilean peso',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CNY',
                'label' => 'Chinese yuan',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'COP',
                'label' => 'Colombian peso',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CRC',
                'label' => 'Costa Rican colón',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CUC',
                'label' => 'Cuban convertible peso',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CUP',
                'label' => 'Cuban peso',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CVF',
                'label' => 'Cape Verdean escudo',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CZK',
                'label' => 'Czech koruna',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DJF',
                'label' => 'Djiboutian franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DKK',
                'label' => 'Danish krone',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DOP',
                'label' => 'Dominican peso',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'DZD',
                'label' => 'Algerian dinar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'EGP',
                'label' => 'Egyptian pound',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ERN',
                'label' => 'Eritrean nakfa',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ESP',
                'label' => 'Spanish peseta',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ETB',
                'label' => 'Ethiopian birr',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'EUR',
                'label' => 'Euro',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FJD',
                'label' => 'Fijian dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'FKP',
                'label' => 'Falkland Islands pound',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GBP',
                'label' => 'British pound',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GEL',
                'label' => 'Georgian lari',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GGP',
                'label' => 'Guernsey pound',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GHS',
                'label' => 'Ghanaian cedi',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GIP',
                'label' => 'Gibraltar pound',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GMD',
                'label' => 'Gambian dalasi',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GNF',
                'label' => 'Guinean franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GTQ',
                'label' => 'Guatemalan quetzal',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'GYD',
                'label' => 'Guyanese dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'HKD',
                'label' => 'Hong Kong dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'HNL',
                'label' => 'Honduran lempira',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'HRK',
                'label' => 'Croatian kuna',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'HTG',
                'label' => 'Haitian gourde',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'HUF',
                'label' => 'Hungarian forint',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'IDR',
                'label' => 'Indonesian rupiah',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ILS',
                'label' => 'Israeli new shekel',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'IMP',
                'label' => 'Isle of Man pound',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'INR',
                'label' => 'Indian rupee',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'IQD',
                'label' => 'Iraqi dinar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'IRR',
                'label' => 'Iranian rial',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ISK',
                'label' => 'Icelandic króna',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'JMD',
                'label' => 'Jamaican dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'JOD',
                'label' => 'Jordanian dinar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'JPY',
                'label' => 'Japanese yen',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'KES',
                'label' => 'Kenyan shilling',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'KGS',
                'label' => 'Kyrgyzstani som',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'KHR',
                'label' => 'Cambodian riel',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'KMF',
                'label' => 'Comorian franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'KRW',
                'label' => 'South Korean won',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'KWD',
                'label' => 'Kuwaiti dinar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'KYD',
                'label' => 'Cayman Islands dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'KZT',
                'label' => 'Kazakhstani tenge',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'LAK',
                'label' => 'Laotian kip',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'LBP',
                'label' => 'Lebanese pound',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'LKR',
                'label' => 'Sri Lankan rupee',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'LRD',
                'label' => 'Liberian dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'LSL',
                'label' => 'Lesotho loti',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'LTL',
                'label' => 'Lithuanian litas',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'LVL',
                'label' => 'Latvian lats',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'LYD',
                'label' => 'Libyan dinar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MAD',
                'label' => 'Moroccan dirham',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MDL',
                'label' => 'Moldovan leu',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MGA',
                'label' => 'Malagasy ariary',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MKD',
                'label' => 'Macedonian denar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MMK',
                'label' => 'Myanmar kyat',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MNT',
                'label' => 'Mongolian tögrög',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MOP',
                'label' => 'Macanese pataca',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MUR',
                'label' => 'Mauritian rupee',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MVR',
                'label' => 'Maldivian rufiyaa',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MWK',
                'label' => 'Malawian kwacha',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MXN',
                'label' => 'Mexican peso',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MYR',
                'label' => 'Malaysian ringgit',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MZN',
                'label' => 'Mozambican metical',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'NAD',
                'label' => 'Namibian dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'NGN',
                'label' => 'Nigerian naira',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'NIO',
                'label' => 'Nicaraguan córdoba',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'NOK',
                'label' => 'Norwegian krone',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'NPR',
                'label' => 'Nepalese rupee',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'NZD',
                'label' => 'New Zealand dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'OMR',
                'label' => 'Omani rial',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PAB',
                'label' => 'Panamanian balboa',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PEN',
                'label' => 'Peruvian nuevo sol',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PGK',
                'label' => 'Papua New Guinean kina',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PHP',
                'label' => 'Philippine peso',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PKR',
                'label' => 'Pakistani rupee',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PLN',
                'label' => 'Polish złoty',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PYG',
                'label' => 'Paraguayan guaraní',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'QAR',
                'label' => 'Qatari riyal',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'RON',
                'label' => 'Romanian leu',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'RSD',
                'label' => 'Serbian dinar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'RUB',
                'label' => 'Russian ruble',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'RWF',
                'label' => 'Rwandan franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SAR',
                'label' => 'Saudi riyal',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SBD',
                'label' => 'Solomon Islands dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SCR',
                'label' => 'Seychellois rupee',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SEK',
                'label' => 'Swedish krona',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SGD',
                'label' => 'Singapore dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SHP',
                'label' => 'Saint Helena pound',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SLL',
                'label' => 'Sierra Leonean leone',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SOS',
                'label' => 'Somali shilling',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SRD',
                'label' => 'Surinamese dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SSP',
                'label' => 'South Sudanese pound',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'STN',
                'label' => 'São Tomé and Príncipe dobra',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SYP',
                'label' => 'Syrian pound',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SZL',
                'label' => 'Swazi lilangeni',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'THB',
                'label' => 'Thai baht',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TJS',
                'label' => 'Tajikistani somoni',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TMT',
                'label' => 'Turkmenistan manat',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TND',
                'label' => 'Tunisian dinar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TOP',
                'label' => 'Tongan paʻanga',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TRY',
                'label' => 'Turkish lira',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TTD',
                'label' => 'Trinidad and Tobago dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TWD',
                'label' => 'New Taiwan dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'TZS',
                'label' => 'Tanzanian shilling',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'UAH',
                'label' => 'Ukrainian hryvnia',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'UGX',
                'label' => 'Ugandan shilling',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'USD',
                'label' => 'United States dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'UYU',
                'label' => 'Uruguayan peso',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'UZS',
                'label' => 'Uzbekistani som',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'VEF',
                'label' => 'Venezuelan bolívar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'VES',
                'label' => 'Venezuelan sovereign bolívar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'VND',
                'label' => 'Vietnamese đồng',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'VUV',
                'label' => 'Vanuatu vatu',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'WST',
                'label' => 'Samoan tala',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XAF',
                'label' => 'Central African CFA franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XAG',
                'label' => 'Troy ounce of silver',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XAU',
                'label' => 'Troy ounce of gold',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XBA',
                'label' => 'European composite unit',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XBB',
                'label' => 'European monetary unit',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XBC',
                'label' => 'European unit of account 9',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XBD',
                'label' => 'European unit of account 17',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XCD',
                'label' => 'East Caribbean dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XOF',
                'label' => 'West African CFA franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XPD',
                'label' => 'Troy ounce of palladium',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XPF',
                'label' => 'CFP franc',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XPT',
                'label' => 'Troy ounce of platinum',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XSU',
                'label' => 'Sucre',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XTS',
                'label' => 'Code reserved for testing',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'XUA',
                'label' => 'ADB Unit of Account',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'YER',
                'label' => 'Yemeni rial',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ZAR',
                'label' => 'South African rand',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ZMW',
                'label' => 'Zambian kwacha',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ZWL',
                'label' => 'Zimbabwean dollar',
                'is_active' => false,
                'is_created' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('currencies')->insert($items);
    }
}
